name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # 4. Log in to Docker Hub (opcional si necesitas hacer push de im√°genes a Docker Hub)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Build and deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # 6. (Opcional) Stop and remove Docker containers after deploy if necessary
      # - name: Stop and remove Docker containers
      #   run: docker-compose down
